language: rust
rust:
  - 1.32.0
  - 1.33.0
  - 1.34.2
  - 1.35.0
  - 1.36.0
  - 1.37.0
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get -y install task
script: |
  cargo build || exit 1
  cargo test || exit 1

  # prepare taskwarrior, initial setup
  yes | task

  cargo run --example create_task | tee /tmp/create_task
  task import /tmp/create_task || exit 1

  cat /tmp/create_task | cargo run --example import_task || exit 1

notifications:
  irc:
    channels:
    - chat.freenode.net#imag
    template:
    - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"
