language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get -y install task
script: |
  cargo build
  cargo test

  # prepare taskwarrior, initial setup
  yes | task

  cargo run --example create_task | tee /tmp/create_task
  task import /tmp/create_task || exit 1

  cat /tmp/create_task | cargo run --example import_task || exit 1

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2 | sed 's/-/_/'`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
notifications:
  irc:
    channels:
    - chat.freenode.net#imag
    template:
    - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"
env:
  global:
  - secure: JQSfBaqgF/QZDo498E0EhpAjtjcq02sMP7c8UoCnFMJLPYGj0EGQM/B0UsvvzwyJnTTodzd/iHQ09CX8updBg2YjyyopW0urcA7la6CRKIV+5mc303OtPHori77VCG5lhsGqMNkm1IWet07aUhvfD/RP1HF0OlMdUGWe7FhczzX0KsiakIv/rUsQoSulMi8svg5a51//FsfUNiVrGS2wfOupjjWneJmEWS+X3pBzY5rCYJNphCPKPDmqYt577UhFV2pbZq1mkF1K6CiIj3fjdaGSMU2gvIrAx9UWXS5qpZQQJyEkv/YVzHqN9P+Cdo6uaJQN1XBrQfCRm3TywsfBKnJasJBUydf/ChJcjdbVzsTYmOdOerwUpAQY7I8YW5TnOdjVtqsSOoPch1vUsh2OSLLOkViwiwC5fZAvpc/b6Ij2kyY07oEAGc2PpBdixss23teTtvRbKtLjgwQCHJf0zJUBqXsjl/CLGXc4UfctxyHMxG3MJkNZt25yzV+c6CWAjOv5ts4pNJBcksD8tmUnkHnDZE1EGFMp3urSW4/N5NC59nl2p2fsz1lpaoYzQweS9jxH0HjnwZJw0/1JksfPjcInBxTDLRfOa/YVPpRTOdlcf2SqU28uCkGOsOaHRKrwVx5MRWmtWH6qRrmgxIh1GaT/JDCg288/lf1QkBjd/bU=
